### ISSUE TITLE
the stimated accuracy with outliers in the point and lines

### ISSUE THREAD

**Issue by weiningwei** [SergioRAgostinho/cvxpnpl#6]
Hi, thanks for the great work.
And I want to estimate the camera pose from the matching points and lines. It is very likely that there is a wrong match, that is an outlier. But I noticed that the datas of point and lines in the example [https://github.com/SergioRAgostinho/cvxpnpl/tree/master/examples](url)   are all noise-free data. So I want to ask if this package can handle such a situation, that with the outlier of data.

**Comment by SergioRAgostinho** [comment]
Most likely not. The performance should decay strongly with outliers.

Why? The cost function that is optimized is a simple squared sum of the residuals for each correspondence. There's no mechanism implemented to mitigate the influence of hard outliers.
