### ISSUE TITLE
Error on Ubuntu 18.04

### ISSUE THREAD

**Issue by alexs7** [SergioRAgostinho/cvxpnpl#7]
Hello,

I am trying to run the examples and I get:

```
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    poses = pnp(pts_2d=pts_2d, pts_3d=pts, K=K)
  File "/usr/lib/python3.6/site-packages/cvxpnpl.py", line 509, in pnp
    return _solve_relaxation(A, B, eps=eps, max_iters=max_iters, verbose=verbose)
  File "/usr/lib/python3.6/site-packages/cvxpnpl.py", line 453, in _solve_relaxation
    max_iters=max_iters,
  File "/usr/lib/python3.6/site-packages/scs/__init__.py", line 166, in solve
    solver = SCS(data, cone, **settings)
  File "/usr/lib/python3.6/site-packages/scs/__init__.py", line 129, in __init__
    **self._settings
ValueError: Error parsing inputs
```

I think it is the SCS version. Do I need to use an older one ? 2.10 ?

**Comment by charlie20s** [comment]
i have find the same error, then i  use SCS==2.1.0、2.1.3、2.1.4 to try the example/pnp.py   and this problem disapper.
However, you may find SCS solver don't work. 

:
FATAL: Cannot solve SDPs with > 2x2 matrices without linked blas+lapack libraries
Install blas+lapack and re-compile SCS with blas+lapack library locations
ERROR: init_cone failure
Setup time: 1.00e-04s
Failure:could not initialize work
Nr of possible poses: 1
R (ground truth):
[[-0.48048015  0.1391384  -0.86589799]
 [-0.0333282  -0.98951829 -0.14050899]
 [-0.8763721  -0.03865296  0.48008113]]
R (estimate):
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
t (ground truth): [-0.10266772  0.25450789  1.70391109]
t (estimate): [nan nan nan]

**Comment by alexs7** [comment]
@charlie20s I used version 2.1.2 and it seems to work.
What do you mean the SCS solver does not work ? With older versions ?

**Comment by SergioRAgostinho** [comment]
Thank you for the heads up. Let me try to replicate it. I just noticed now that scs is already in major version 3. When I published this, it just came out of version 2, so it's likely the interface might have changed. 

I'll have a look.

**Comment by charlie20s** [comment]
> 
@alexs7  the result of R,t(estimate) is all [nan]

**Comment by SergioRAgostinho** [comment]
I've replicated the problem on my end and the errors start appearing with scs versions >= 3.0.0. The latest version working for me  is 2.1.4. So use that one temporarily until I patch this.

**Comment by charlie20s** [comment]
> thanks for you work.

I find that when i use SCS 3.0.0 and  remove the words eps in the function _solve_relaxation(A, B, eps=1e-9, max_iters=2500, verbose=False) in cvxpnpl.py
like this: 
        verbose=verbose,
        # eps=eps,
        max_iters=max_iters,
than the example of (pnp.py, pnl.py, pnpl.py ) all work. but it show:

D:\0Work\cvxpnpl\cvxpnpl.py:483: UserWarning: The solution is not certifiably optimal.
  warnings.warn(not_certifiable) 

So the eps is a Optimization parameters? 

 I hold this information may be useful.

**Comment by SergioRAgostinho** [comment]
I just finished patching and uploading a new version that adds support to SCS 3.x.x and solves the issues you've experienced before. To test it just install it with 
```
pip install cvxpnpl==1.1.0
```
from inside your python environment. 

Thank you for reporting the issue.

**Comment by alexs7** [comment]
great! thanks!
