### ISSUE TITLE
4 solutions ?

### ISSUE THREAD

**Issue by alexs7** [SergioRAgostinho/cvxpnpl#8]
Hello,

Given 4 matches, the solutions number should be 1 ?
I get 4. which one of the 4 is the correct one ?

Thanks

**Comment by SergioRAgostinho** [comment]
Sorry for delayed reply. 

> Given 4 matches, the solutions number should be 1 ?

Correct.

> I get 4. which one of the 4 is the correct one ?

I suspect all your 4 points are co-planar. You would get 4 solutions in that case.

**Comment by alexs7** [comment]
Ok so I need to get better matches. Thanks!
